# Generated by Django 3.0.5 on 2021-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('price', models.FloatField(verbose_name='mac price')),
                ('rating', models.IntegerField(default=0)),
                ('informations', models.CharField(max_length=255)),
            ],
        ),
    ]
